### ISSUE TITLE
[Feature request]: PDF Import

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodCloud/Butterfly#106]
### Describe your feature request!

Add pdf import using the insert dialog

### Additional context

https://pub.dev/documentation/printing/latest/printing/PdfRaster/asImage.html

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shahin-rmz** [comment]
currently, xournal++ does import pdf and we can annotate on our pdfs.
If we can do this on Butterfly, well, it can take place of xournal as well.
(In linux/ open source world we do not have much more options right now).

**Comment by CodeDoctorDE** [comment]
My current problem is that there is currently no opensource library for flutter for pdf import.
I need to make my own to support this.

**Comment by Shahin-rmz** [comment]
Not very familiar with Flutter.
But maybe you can import them as png.
or vectorize the text of the pdf.
(just rough idea.)

**Comment by CodeDoctorDE** [comment]
Yeah. But I don't know if I can reimplement all features of the pdf format.
Flutter supports adding c++ to the native platform and adding additional javascript on the web. With that we can use libraries of other languages in the application. Currently I haven't used this featuer and need to look how it works.

**Comment by Shahin-rmz** [comment]
would be interesting.

**Comment by CodeDoctorDE** [comment]
Okay I found two libraries that can be used:
* For c++: https://pdfium.googlesource.com/pdfium/ (From Google, used in chrome)
* For web: https://mozilla.github.io/pdf.js/ (used by firefox)
