### ISSUE TITLE
[Bug]: F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [LinwoodCloud/Butterfly#140]
### What happened?

```
FAILURE: Build failed with an exception.

* Where:
Build file '/home/vagrant/build/dev.linwood.butterfly/app/android/app/build.gradle' line: 38

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'ndkVersion' for extension 'flutter' of type FlutterExtension.
```

Could you please take a look? Thanks!

### Version

1.3.0-alpha.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Strange...
Do you use the latest flutter beta?
Do you use:
```bash
cd app
flutter pub get
flutter build apk
```

**Comment by linsui** [comment]
We still using 2.10.1. I'm testing it with 2.13.0-0.1.pre.

**Comment by CodeDoctorDE** [comment]
Does it work?

**Comment by linsui** [comment]
It works! Thanks!
