### ISSUE TITLE
[Feature request]: embedded Butterfly

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#144]
### Is your feature request related to a problem? Please describe

Yes, there are multiple apps which use other programs as a solution for their annotating problems.
for example Bookstack, Dokuwiki, etc.
It would be awesome, if we could embed Butterfly inside other programs (wiki's in particular). 

### Describe your feature request!

[embed mode](https://www.diagrams.net/doc/faq/embed-mode) is very interesting feature, which allows developers connect one app to another app. It benefits users in order to make them able to enjoy both worlds of two app.
If we can have embed mode of Butterfly, in order to use it (specially in wikis) it would add so much value to Butterfly and wiki.
Personally I use Dokuwiki, and mobile app does not have any note taking ability.
[list of self hosted wikis](https://alternativeto.net/category/education-and-reference/wiki/?platform=self-hosted)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Okay sounds very interesting. Should I make my own api or are there any requirements?

**Comment by Shahin-rmz** [comment]
As I am seeing, no need for API.
their app should be able to "open" Butterfly. and all will be done inside Butterfly.
(In Desktop, Web or mobile version).
Other approach is to have json and API, which requires developing an API.

**Comment by Shahin-rmz** [comment]
![image](https://user-images.githubusercontent.com/32805117/163713485-09b7b9fd-ad87-4ca1-9992-bdb73e0b7c55.png)
check it out [here](https://www.bookstackapp.com/).
login to demo and try to draw something.

**Comment by CodeDoctorDE** [comment]
Seems they are working with events. I will look at it
