### ISSUE TITLE
[Feature request]: Make Butterfly sync and ready flow the ideas.

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#145]
### Is your feature request related to a problem? Please describe

Consistency is very important in large projects.
It can happen, that a user is working on an idea on the desktop, and wanted to continue working on it on mobile, or tablet later in the week.
To have a server, where can save the data, and users can call it later would be good idea.

### Describe your feature request!

connecting Butterfly to a server side application, which can be hosted on our own computer severs, and we can connect to our accounts from Mobile app/ Web app or desktop app.
something like [Nextcloud](https://nextcloud.com/clients/#:~:text=The%20Nextcloud%20Android%20app%20makes,screen%20sizes%20and%20Android%20features.)
which we can have different instances but all show our own data.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shahin-rmz** [comment]
I can help you if you want to write server side application in Fastapi.
It's in Python.

**Comment by CodeDoctorDE** [comment]
I don't know if production ready is the right term. Other applications has no backend too and live for years.
A server to save data is a good idea. But I don't know if you need something. For example #87 can solve this problem too. Then I don't need to handle user authorization (which can be a huge security risk) and can focus on the app.
A server can be good for having collaborative editing.

**Comment by Shahin-rmz** [comment]
Yes it is duplicate of that feature.
I didn't mean having multiple users.
Please accept my apologies.
