### ISSUE TITLE
[Documentation]: what is it???

### ISSUE THREAD

**Issue by strider72** [LinwoodCloud/butterfly#16]
### What happened?

How do you expect people to discover your app when you don't tell us what it is? Marketing!

I had to come to the github just to see that it's a notes app, and I know nothing beyond 1) notes app, 2) stores data locally, and 3) customizable.  You should put at least a sentence or two in the readme talking about what it is :-)

 

### Version

2.0.0-beta.0 (Latest release)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I will try my best, to add more things to the readme. If you want to help me feel free to create a pull request.

**Comment by CodeDoctorDE** [comment]
The app should be self explaining when you go to the web version: https://butterfly.linwood.dev

**Comment by natrius** [comment]
Does not matter if I never even download the app because I don't know what it is.
If I browse through f-droid I will never know there is an webversion as well.

```
## Your data will be saved locally

Everything will be saved local on your computer. The data is saved in json files.

## Customizable

Change everything to your needs. Choose your custom color, create a palette and add your pages to the paper.
The paper has an infinite size, perfect for your ideas and notes.
```

Thats all :D

**Comment by CodeDoctorDE** [comment]
https://github.com/LinwoodCloud/butterfly#introduction
Do you know what I can change? I added a short summary and `Simple and intuative`

**Comment by NESC1US** [comment]
I think this is changeable in f-droid, not here

**Comment by natrius** [comment]
Dunno what you mean @NESC1US , it should be changed here. @CodeDoctorDE changed https://github.com/LinwoodCloud/butterfly/blob/develop/fastlane/metadata/android/en-US/full_description.txt already and i added the description now to https://github.com/LinwoodCloud/butterfly/blob/develop/fastlane/metadata/android/en-US/short_description.txt as well if CodeDoctorDE will accept the Pull request https://github.com/LinwoodCloud/butterfly/pull/38 :)

After that, it should be better in F-Droid as well.

**Comment by natrius** [comment]
Additionally, you might get inspiration for the readme from https://github.com/othneildrew/Best-README-Template - in case you want to expand the readme :)

**Comment by CodeDoctorDE** [comment]
> Additionally, you might get inspiration for the readme from https://github.com/othneildrew/Best-README-Template - in case you want to expand the readme :)

My goal from the readme was to be minimalistic. The license can be found in the LICENSE file, the contribution guide in CONTRIBUTION.md and the getting started was linked to the docs

**Comment by CodeDoctorDE** [comment]
https://f-droid.org/de/packages/dev.linwood.butterfly/ It should be on fdroid :=)
