### ISSUE TITLE
Re-release last version to trigger the winget-releaser action

### ISSUE THREAD

**Issue by vedantmgoyal2009** [LinwoodCloud/Butterfly#160]
### What happened?

Hi @CodeDoctorDE,

I'm sorry for the problems caused because the action wasn't working. I have fixed all the bugs now and tested them. Everything seems now to be working as expected.

Before you proceed, please grant `read:org` and `read:discussion` permission to `CI_PAT` token. They are need because the PR has to be made at `microsoft` which is an organisation, and not a user.

Also, do not add release binaries after publishing the release since then the webhook will be empty.

### Version

N/A

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I added these flags and rerun it, but I get this error:
```
Error: vedantmgoyal2009\vedantmgoyal2009\v1.0.0\winget-pkgs-automation/releaser-action\action.yml (Line: 96, Col: 25): A sequence was not expected
Error: The template is not valid. vedantmgoyal2009\vedantmgoyal2009\v1.0.0\winget-pkgs-automation/releaser-action\action.yml (Line: 96, Col: 25): A sequence was not expected
Error: The CancellationTokenSource has been disposed.
```

**Comment by vedantmgoyal2009** [comment]
I really don't know from where it comes, may be from inside of github actions itself since I didn't write any complex logic.

I have used `ConvertFrom-Json` now, so it shouldn't throw an error now. Also, you can now remove `read:org` and `read:discussion` since they are no longer needed.

**Comment by CodeDoctorDE** [comment]
```
Exception: D:\a\Butterfly\Butterfly\winget-pkgs-automation\winget-pkgs\Tools\YamlCreate.ps1:896
Line |
 896 |              Throw 'Number of InstallerUrls are not equal'
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Number of InstallerUrls are not equal

```

**Comment by vedantmgoyal2009** [comment]
Can you please try now? I'm pretty sure it should succeed now.

**Comment by vedantmgoyal2009** [comment]
You didn't fork the winget-pkgs repo in @linwoodcloud.

**Comment by CodeDoctorDE** [comment]
But why does it add 1.3.0 instead of 1.3.0-beta.1?

**Comment by vedantmgoyal2009** [comment]
> But why does it add 1.3.0 instead of 1.3.0-beta.1?

* Opened pull request #161

**Comment by CodeDoctorDE** [comment]
> Hello @CodeDoctorDE, I am sorry to report that the Sha256 Hash does not match the installer. This maybe caused by using a vanity URL rather than a URL directly to the binary.
> 
> Please check the HASH and submit again. Sorry for the inconvenience.

https://github.com/microsoft/winget-pkgs/pull/59699#issuecomment-1119772595

**Comment by vedantmgoyal2009** [comment]
Please commit the suggested changes.

**Comment by CodeDoctorDE** [comment]
But does this happens in the next release again?

**Comment by vedantmgoyal2009** [comment]
It happens with the automation too, when the file from GitHub Release is not correctly downloaded. Or sometimes, the manifest validation pipelines may have errors in downloading the Installer Url from the manifest.

It doesn't happen always and if there will be any bug from my side, it will affect both in the automation and the action since action itself uses the core files from he automation.

**Comment by CodeDoctorDE** [comment]
Should I change the workflow to start on every release?
Currently the pre-releases will be ignored
