### ISSUE TITLE
[Bug]: Cannot insert images in web

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodCloud/Butterfly#167]
### What happened?

Currently decoding images does not work with canvaskit.
Please upvote [this issue](https://github.com/flutter/flutter/issues/102683) if you want this option!

### Version

1.3.0-rc.0

### Platform

Web

### Relevant log output

```shell
Error: Failed to encode the image into bytes.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Shahin-rmz** [comment]
This issue happens to me when I testing the last version.
tried on both chromium (brave) and Firefox version.

**Comment by CodeDoctorDE** [comment]
On firefox it should work. Only on chromium browsers should happen the issue

**Comment by CodeDoctorDE** [comment]
Fixed in 1.5.0

**Comment by CodeDoctorDE** [comment]
Fixed in 1.6.1 with Flutter 3.7.0
