### ISSUE TITLE
[Bug]: Unintuitive UX when starting using the app.

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#17]
### What happened?

It is tricky to find out what is this app about without too many clicks.

Here is my scenario:

1. Open Butterfly
2. Assuming it's some graphical notes app, try drawing something with a finger at that empty dark gray space.
3. Nothing happens. Notice "[+ Create]" button at the bottom.
4. Create a project (begrudgingly typing something as a name). I expect many casual users may just uninstall the app instead.
5. Notice project name with delete button appearing at the top. Try drawing something again. Nothing happens.
6. Tap at the button with project name. White background opens. Draw something.
7. Again nothing happens.
8. Try zooming in and out using pinch gesture. Zoom level seems to change, but still cannot draw anything.
9. Notice palette button at the bottom. Maybe it's just white colour by default? Open it and select some distinct colour. Try drawing again. Nothing happens.
10. Try various buttons. Finally the strange hand button changes to pencil button and it starts actually drawing content.

Expected:

1. Open Butterfly app for the first time.
2. Default project is created and is pre-opened. Drawing mode is the default, so user can immediately produce content.

Version: 1.0.0-rc.1 from F-Droid.

### Version

2.0.0-rc.0 (Latest snapshot)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
The home page is the drawing pad now. Try it and give feedback: https://butterfly-git-feature-draw-home-page-linwood.vercel.app/

**Comment by vi** [comment]
It is now much better.

Further "first startup" improvements (e.g. interactive tutorial) should be tracked as a separate issue.
