### ISSUE TITLE
[Feature request]: Save As ...

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#180]
### Is your feature request related to a problem? Please describe

Yes, syncing and accessing the data for the users can be smoother.

### Describe your feature request!

Hello,
again I love using Butterfly. Thanks to make this app for humanity.

If we want to save (or export) our drawings we have some options:
1. save button, where a `bfly` file will be saved in cash of our browser (or somewhere else).
2. export as `SVG`
3. export as *Data*
4. export as an *image*

How ever, there is lack of one crucial button. The user should be able to save `bfly` to whatever folder they like, and then open it with another device or work with it later.

### Additional context

Here is my desired scenario.
There is a `Save As` option in the menu or navbar,
- User saves the `bfly` file in a shared folder (Nextcloud for example)
- User opens another device(mobile) and run the the `bfly` file with the mobile and continiue their work there.
- user saves the data on the `nextcloud` folder on their mobile
- Continue working on the file with computer later.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That's an interesting idea...
I don't know if a button "Save as" would look good if we don't have a "Save" button in the menu.
Maybe add it to the "Change document path" dialog? From there you can "copy" and "move" the document.

**Comment by Shahin-rmz** [comment]
Nice, looking forward to it.
