### ISSUE TITLE
[Feature request]: image import on android

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#181]
### Is your feature request related to a problem? Please describe

working on images are as important as working on pdfs.
pdf is implemented and we need images as well.

### Describe your feature request!

As mentioned, there are cases, where user takes a photo **with mobile** and wants to work on it.
In these cases the Butterfly app can be very helpful.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This is already working
Click on the background
![image](https://user-images.githubusercontent.com/20452814/171541674-6a6a3bbf-223c-4998-8605-f37a51c39936.png)
Click on insert
![image](https://user-images.githubusercontent.com/20452814/171541765-106e47d0-2e55-44cd-acac-9457108275c8.png)
Click on image (or camera if you want to take a picture)

**Comment by Shahin-rmz** [comment]
Thanks, I was using Linux and android version.
I thought feature has not been implemented yet.
I will use Web version from now on.

**Comment by CodeDoctorDE** [comment]
Noo, the web version has a known bug with images #167

**Comment by Shahin-rmz** [comment]
So which platform should I use?
:D

**Comment by CodeDoctorDE** [comment]
The native platform. There is a download/app store version for android

**Comment by CodeDoctorDE** [comment]
Oh yeah, seems the template file is corrupted. I will add a reset button to it. Can you please create a new issue for this?

**Comment by Shahin-rmz** [comment]
> Can you please create a new issue for this?

Sure.
Just later on.
