### ISSUE TITLE
[Bug]: unlimited spinning in Android app

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#183]
### What happened?

A bug happened!
When I open the app, the "create dialogue" spins for unlimited time.
If I click outside the dialogue, it will go away.

### Version

1.3

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Yes, Fdroid and Play Store takes 3-5 days to accept it.
