### ISSUE TITLE
[Bug]: resize image and PDF

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#184]
### Is your feature request related to a problem? Please describe

This is an advantage, that we can import multiple images and PDFs into the app. and make notation on them without hassle.
But it can happen, that we may want to resize an image or a page of pdf.
if it is possible to be able to resize each object (text, vector, image, pdf) it would be goof idea.
Most important one, are images and pdfs.

### Describe your feature request!

resizing the imported images or pdfs are crucial feature for the people who import many resources and annotate them.
If we can have a "resize" option alongside "move" option.

### Additional context

I think this feature will help most the researchers and students and people in academic area.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Fixing this for 1.3...
