### ISSUE TITLE
[Bug]: Moving in Mobile is not optimal

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#185]
### Describe your feature request!

When we move an object, that happen that the object comes at utmost right down of our finger tipp.
in computer it's ok, but in mobile, the UX will be better if the object is at the center of touch point.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Does it happen only on images? It should be the same on desktop

**Comment by Shahin-rmz** [comment]
> Does it happen only on images?

No, on pdfs also.

**Comment by CodeDoctorDE** [comment]
Yes, pdfs will be rendered as images. I'm working on it

**Comment by CodeDoctorDE** [comment]
Fixing this for 1.3...
