### ISSUE TITLE
[Feature request]: MacOS Support

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodCloud/Butterfly#191]
### Describe your feature request!

On macos you can install apps using a dmg file. You don't need to pay for a license in the app store.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
If anyone has a mac and interest adding a macos build, feel free to create a pull request!

**Comment by CodeDoctorDE** [comment]
Closed via #245

**Comment by CodeDoctorDE** [comment]
@batuhand The tar.gz is currently not runnable. Can you try help me

**Comment by batuhand** [comment]
> @batuhand The tar.gz is currently not runnable. Can you try help me

The file that I uploaded is .app file and it is built for macOS. It will not run if you try inside any other os.

**Comment by CodeDoctorDE** [comment]
A user reported it on discord after renaming .tar.gz to .app:

`You can’t open the application “butterfly” because this application is not supported on this Mac.`

**Comment by batuhand** [comment]
It may be about Apple m1 chip, app is built in an intel chip MacBook

**Comment by CodeDoctorDE** [comment]
Have you tested it on your device. And how should I package it instead? I don't know if macos can run tar.gz

**Comment by batuhand** [comment]
> Have you tested it on your device. And how should I package it instead? I don't know if macos can run tar.gz

Yes it is tested. It can be seen as .tar.gz if you are not using macOS

**Comment by Centritide** [comment]
Hello, I've downloaded the nightly release on both an m2 mac and an intel mac – both show as .tar.gz, and changing it to .app doesn't work on either. Might be an issue with the download? Is the file hosted somewhere that treats it as .tar.gz?

**Comment by batuhand** [comment]
> Hello, I've downloaded the nightly release on both an m2 mac and an intel mac – both show as .tar.gz, and changing it to .app doesn't work on either. Might be an issue with the download? Is the file hosted somewhere that treats it as .tar.gz?

Hi, it can be a packaging issue then. I'll check and see what we can do about it.
