### ISSUE TITLE
[Bug]: F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [LinwoodCloud/Butterfly#197]
### What happened?

```
Expected to find fonts for (packages/phosphor_flutter/Phosphor, packages/cupertino_icons/CupertinoIcons, MaterialIcons), but found (MaterialIcons, packages/phosphor_flutter/Phosphor). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
Note: /home/vagrant/.pub-cache/hosted/pub.dartlang.org/printing-5.9.1/android/src/main/java/net/nfet/flutter/printing/PrintingPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Expected to find fonts for (packages/phosphor_flutter/Phosphor, packages/cupertino_icons/CupertinoIcons, MaterialIcons), but found (MaterialIcons, packages/phosphor_flutter/Phosphor). This usually means you are referring to font families in an IconData class but not including them in the assets section of your pubspec.yaml, are missing the package that would include them, or are missing "uses-material-design: true".
Running Gradle task 'assembleRelease'...                          315.2s
Gradle build failed to produce an .apk file. It's likely that this file was generated under /home/vagrant/build/dev.linwood.butterfly/app/build, but the tool couldn't find it.
```

Could you please take a look? Thanks!

### Version

1.4.0-alpha.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Yeah,
That's a new addition for the android setup. I'm using the flavor feature of flutter.
I have two flavors:
* `development`
*  `production`

The only difference is the icon. I would prefer adding `--flavor development` to the build command and use the location `build/app/outputs/flutter-apk/app-development-release.apk`.

The current alpha has a wrong namespace. I will release a new version with the fixed namespace in a few days

**Comment by linsui** [comment]
Thanks!

**Comment by CodeDoctorDE** [comment]
Hello,
I think I forgot something.
Can we add `--flavor development` only if  a `-` is in the version name?
The default flavor should be `--flavor production` to have the default look of the app.

**Comment by linsui** [comment]
The fdroidserver can only copy the last build block... So you can make a MR when the flavor needs to be changed or add a new flavor which behave differently according to the version.

**Comment by CodeDoctorDE** [comment]
Oh okay. Or we can ignore these flavors and use the default one. It's not very ideal but can solve the issue that currently every release gets a blue icon

**Comment by linsui** [comment]
Yes, you can add a nightly channel with another appid.

**Comment by CodeDoctorDE** [comment]
I have added dev.linwood.butterfly.nightly when using `flutter build apk --flavor nightly`.

How should I submit it to f-droid?
I want two channels

## dev.linwood.butterfly

Here only versions starting with `v` and no `-` should be published.
I have built a small regex for this `v([0-9]|\.)+`.

## dev.linwood.butterfly.nightly

Here all versions should be published.
A regex can be `v.+`.

**Comment by linsui** [comment]
With `flutter build apk --flavor nightly` I got a wrong app id. https://gitlab.com/linsui/fdroiddata/-/jobs/2666924562 Any idea?

**Comment by CodeDoctorDE** [comment]
Yes,
>  Yes, you can add a nightly channel with another appid.
You say to have two channels (nightly and stable) we need two app ids.

To get the nightly version (appid: `dev.linwood.butterfly.nightly`) we need `flutter build apk --flavor nightly`.
For this we need a new metadata file in the fdroid repo.

To get the normal version (appid: `dev.linwood.butterfly`) we can use `flutter build apk --flavor production`. This should be the existing metadata file.

**Comment by linsui** [comment]
The problem is that with the nightly flavor I got `dev.linwood.butterfly`.

**Comment by linsui** [comment]
Ah, I got it. I remove that line...

**Comment by CodeDoctorDE** [comment]
Which line?  I'm currently investigating why this happen

**Comment by linsui** [comment]
In the previous version I removed the suffix to make it build a apk with the original ID. I forgot to remove that... https://gitlab.com/linsui/fdroiddata/-/commit/42f27a11b4a836c5320e0a0f7b2518562520785c#409a95055dedb7f5ea79688aeb4873019ed3a9ba_0_34

**Comment by linsui** [comment]
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11265

**Comment by linsui** [comment]
If you don't put them in the fastlane they'll be extracted from the apk. To use different fastlane metadta you can use triple-t instead. See https://gitlab.com/-/snippets/1901490
