### ISSUE TITLE
[Bug]: Zooming using gesture while in drawing mode draws a weird zigzag

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#20]
### What happened?

1. Open project.
2. Switch to drawing mode
3. Zoom out using two-finger pinching gesture.

Expected: drawing is suppressed while zooming or panning using two fingers and only changes content when single finger touches the screen.
Actual: It zooms out, but also paints a lot of zigzagging line segments.

Those extra lines seem not to be considered as part of the project and tend to disappear when continuing editing.

Version: 1.0.0-rc.1 from F-Droid.

### Version

2.0.0-rc.0 (Latest snapshot)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Already fixed. I will publish the next release candidate soon
