### ISSUE TITLE
[Documentation request]: Switching the codebase to AGPL 3

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodCloud/Butterfly#202]
### To which page is your issue related?

https://github.com/LinwoodCloud/Butterfly/blob/develop/LICENSE

### Describe your documentation request!

GPL is a great license for an opensource application. Everyone can contribute, change the code when keeping the source public.
The problem is, that you can add service around it without keeping the project public. AGPL solves it. It has an extra requirement to solve the issue.

Read more here: https://plausible.io/blog/open-source-licenses

### Additional context

@vedantmgoyal2009 @kant 
Please comment (not react) with :+1: if you agree with it. You have added some commits to the project and have the right to deny this.
Any commits of you will be undone to protect your right.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vedantmgoyal2009** [comment]
👍

**Comment by CodeDoctorDE** [comment]
@kant Please comment with 👍 if you agree with the license change. I can't change it before all contributors accept it.

**Comment by kant** [comment]
👍
