### ISSUE TITLE
[Bug]: Unable to run Butterfly AppImage

### ISSUE THREAD

**Issue by manikandancode** [LinwoodCloud/Butterfly#204]
### What happened?

Ubuntu 22.04 Wayland
[Linwood-Butterfly-linux-x86_64.AppImage](https://github.com/LinwoodCloud/Butterfly/releases/download/v1.3.2/Linwood-Butterfly-linux-x86_64.AppImage)

![Screenshot from 2022-07-01 09-28-48](https://user-images.githubusercontent.com/46480489/176843174-e5bec405-7d4f-4b93-a5f7-4509c5d6f870.png)

### Version

1.3.2

### Platform

Linux

### Relevant log output

```shell
Check attached image
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Maybe this can happen because of wayland. I will try it on my machine.

**Comment by CodeDoctorDE** [comment]
I think I fixed the bug.
Can you try this appimage? https://github.com/LinwoodCloud/Butterfly/suites/7177536207/artifacts/286261405
You can also use the deb package, the portable version or the flathub version. These are working fine

**Comment by CodeDoctorDE** [comment]
I can't upload it here...
I will try to compress the size

**Comment by manikandancode** [comment]
https://github.com/LinwoodCloud/Butterfly/suites/7177536207/artifacts/286261405

![Screenshot from 2022-07-04 13-27-08](https://user-images.githubusercontent.com/46480489/177143643-bc51ae61-632b-4463-84e8-6b4435a9c716.png)

**Comment by CodeDoctorDE** [comment]
I tested it on my device and it works now. Can you try the latest 1.4.0 release?

**Comment by CodeDoctorDE** [comment]
Please reply if you have any issues. I will close this issue.
