### ISSUE TITLE
[Feature request]: Add offline-sync functionality

### ISSUE THREAD

**Issue by prateekmedia** [LinwoodCloud/Butterfly#205]
### Is your feature request related to a problem? Please describe

Currently we can only save the notes offline but let's say I have two or more devices then It can easily become a mess to keep the notes update to date on all of them.

### Describe your feature request!

Add some kind of sync, Like google drive, onedrive or dropbox.

### Additional context

This will be needed also cause every other notes app has this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
The basic functionality is already available on the nightly version (#87 ).

I will use the issue to track the offline-sync functionality.
