### ISSUE TITLE
[Feature request]:  Eraser painter draws strange

### ISSUE THREAD

**Issue by Sudo-Adrian** [LinwoodCloud/Butterfly#209]
### Describe your feature request!

Der Ereaser ist verwirrent wenn man zeichnet. Es sieht so aus, als wenn man zeichnen würde. Ein Kreis wo man einen gestrichelten umfang eines Kreises sehen würde wäre besser
Trotzem cooles Projekt!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Translated:
> The eraser is confusing when drawing. It looks like drawing. A circle where you would see a dashed perimeter of a circle would be better
Still cool project!

Thanks. To improve the performance you draw with a white painter while you are drawing the path. After releasing the pen/mouse/finger it should work normally
