### ISSUE TITLE
[Bug]: Switching to drawing mode resets zoom level

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#21]
### What happened?

1. Open some project
2. Zoom in to draw finer details or zoom out to fill in larger area.
3. Switch to drawing mode

Expected: zoom level stays the same. Default brush size depends on current zoom level.
Actual: zoom level resets to 100.00.

Version: 1.0.0-rc.1 from F-Droid.

### Version

2.0.0-rc.0 (Latest snapshot)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Related to #20

**Comment by vi** [comment]
The issue is marked as resolved, yet on https://butterfly.linwood.dev I still see zoom resets when I begin drawing after zooming in view mode.

**Comment by CodeDoctorDE** [comment]
You  can find the development version here: https://preview.butterfly.linwood.dev
