### ISSUE TITLE
[Feature request]: Native window decoration support

### ISSUE THREAD

**Issue by tio-trom** [LinwoodCloud/Butterfly#219]
### Is your feature request related to a problem? Please describe

Many operating systems rely on their own window decoration for all sorts of features + consistency in usability. The problem is that I cannot right click the top bar of your app and send it to a different screen, add it on top of other windows, make it visible on all workspaces, and so forth. Thus, functionalities are removed.

### Describe your feature request!

Enable native window decorations as default please :). 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I chose the custom title bar to reduce the size that the gui takes.
I don't know if it works on linux but on windows the right click menu still opens when clicking on a free space in the custom title bar. There was a bug in the rc.0 version which was fixed in the rc.1. Which version do you use?

The native title bar can be still added, but I don't want to put it as default.

**Comment by tio-trom** [comment]
Ah that's true if you click on certain areas it brings up the system's menu....it is not that intuitive since you have to find the right spot to click...

I am using the 1.3.2 version That's what it says.

> The native title bar can be still added, but I don't want to put it as default.
Is there an option now for this? I cannot see it. Thanks!

**Comment by CodeDoctorDE** [comment]
> Ah that's true if you click on certain areas it brings up the system's menu....it is not that intuitive since you have to find the right spot to click...
> 
> I am using the 1.3.2 version That's what it says.

I think in the latest rc, the spot is bigger. Can you try it?

> Is there an option now for this? I cannot see it. Thanks!

Currently not, I don't know if it is so important

**Comment by tio-trom** [comment]
> I think in the latest rc, the spot is bigger. Can you try it?

As soon as the flatpak gets updated I will and let you know, however I'd so appreciate if you can also add a system window decoration option...from my perspective it is far more useful and usable. On top of what I said there are many functionalities of a system window decoration....one can tweak it, move the buttons to the left side, integrate the window bar with the system's top bar, and more. I am saddened to see that more apps choose not to respect the system's theme and window decoration.

I much appreciate your work don't get me wrong, but I wanted to make sure you also understand my point.

**Comment by CodeDoctorDE** [comment]
Sure okay. I will add it to 1.4.1.
The app is currently in release candidate state.

**Comment by tio-trom** [comment]
> Sure okay. I will add it to 1.4.1. The app is currently in release candidate state.

Oh you are so wonderful! I appreciate it so much. And wonderful app of course. Thanks a lot!

**Comment by CodeDoctorDE** [comment]
![image](https://user-images.githubusercontent.com/20452814/180475337-33032bc6-24ff-4ea1-909a-4997be572c51.png)
This should be it! Can you please test it? Maybe I will put it in the next version.

Here the download link for the portable version: https://github.com/LinwoodCloud/Butterfly/suites/7480490118/artifacts/306794217

**Comment by tio-trom** [comment]
I would love to test it but am unsure how to exactly to be honest.

**Comment by CodeDoctorDE** [comment]
You can enable it in the personalization settings (Click on the left top corner, click on settings, personalization)

**Comment by tio-trom** [comment]
Sorry I meant how to install on Arch Linux...I am unsure of that to be honest, from the zip you sent.

**Comment by CodeDoctorDE** [comment]
You need to unzip it and run the butterfly file

**Comment by tio-trom** [comment]
I understand, I tried that but there is no way my system will open it.

```
~/Downloads/linux-build >>> butterfly                                       [1]
zsh: command not found: butterfly

```
I made the butterfly file executable too. Nothing....maybe am missing something...

**Comment by CodeDoctorDE** [comment]
If you run `ls` you should see a `butterfly` file.
Run `chmod +x butterfly` to make it executable.
After that you can use `./butterfly` to run it

**Comment by tio-trom** [comment]
Ah the `./butterfly` was the key. Works now. Tested. Native window decoration works! I appreciate this a lot!

**Comment by CodeDoctorDE** [comment]
Thanks for your feedback!
