### ISSUE TITLE
[Bug]: Selecting objects fail after zooming using fingers gesture.

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#22]
### What happened?

1. Open project where there is some object (e.g. brush stroke) is present.
2. Zoom in or out using pinch gesture.
3. Try to select object to deletion by tapping it in panning mode.

It fails.

If only panning or zooming using toolbar buttons were used (not using gesture) then it continues to work.

Version: 1.0.0-rc.1 from F-Droid.

### Version

2.0.0-rc.0 (Latest snapshot)

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Strange that it doesn't work. I will look at it!

**Comment by CodeDoctorDE** [comment]
Oh, same bug as #20. Already fixed
