### ISSUE TITLE
The dark text colors are very hard to read 

### ISSUE THREAD

**Issue by amarradi** [LinwoodCloud/Butterfly#226]
### What happened?

The dark text colors are very hard to read. You should Update the dark Theme colors 
![Screenshot_20220726-132001](https://user-images.githubusercontent.com/720573/180994987-3ae640e5-17d3-4288-beb1-767d418da74c.png)

### Version

1.4.0-RC.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
It was already fixed
> Fix classic light theme

https://docs.butterfly.linwood.dev/changelog#140-rc2-2022-07-23

It takes a while that the store accepts the update.
