### ISSUE TITLE
[Feature request]: PDF in, PDF out 

### ISSUE THREAD

**Issue by Shahin-rmz** [LinwoodCloud/Butterfly#235]
### Is your feature request related to a problem? Please describe

often happens, that people in academic area, (students, professors and researchers) need to import a PDF, do some comments and notations, and share it to others. They do not want to have a board or extra place, but just a PDF as place to take a note.

### Describe your feature request!

It would be useful if there is a feature, that Butterfly app would import PDF and just show it without separating the pages, and also **Export** the pdf when the notation is done. just as easy as 1 click.
This will help students and teachers and researches who want to note on a paper.

### Additional context

currently Butterfly can work with PDF, almost with no problems.
What I mean is something like Xournal++, (But in Butterfly way) to import, work with, and export pdfs without taking care of the whole board.
Just a minimalistic environment without additional spaces, which makes it easy to **export as pdf**.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Import is already possible (you can even choose the pages to import), exporting is tracked [here](#188).

**Comment by Shahin-rmz** [comment]
Oops , it seems that this request is duplicate of #188.
I will delete it
