### ISSUE TITLE
[Feature request]: Eraser and Pen Improvements

### ISSUE THREAD

**Issue by lilbud** [LinwoodCloud/Butterfly#237]
### Describe your feature request!

Not sure how possible this would be, but maybe support for Pressure Sensitive input when drawing and erasing? Either finger input or pen input, basically create a larger stroke when writing with more pressure. 

Another request would be an outline for the eraser, it's kind of hard to tell where is being erased, moreso when the eraser size is bigger and all that is on screen is a little dot.

### Additional context

I come from using Microsoft Whiteboard but have been searching for a replacement since Microsoft's recent update to that basically made it unusable for me. So, these are a few features I'd like to request for this software. Actually completely found this software on a whim while scrolling through Reddit,

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hello,
Thank you for your issue.
Pressure sensing is already possible in the web and android.
What do you mean with outline? Currently you are painting with the background color while erasing.
Nice to see you here. I created the post a half hour ago.

**Comment by lilbud** [comment]
![image](https://user-images.githubusercontent.com/9311410/183137393-89e5b48f-d87c-49e2-9c64-a5b38afe0a60.png)
Tried to get a pic while also drawing on Microsoft Whiteboard, basically showing the path of the eraser.

**Comment by CodeDoctorDE** [comment]
Oh that looks good.
I will add this in the next release.

**Comment by CodeDoctorDE** [comment]
Can you try https://preview.butterfly.linwood.dev ?
