### ISSUE TITLE
[Bug]: Templates unavailable after changing storage location on Android

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#254]
### What happened?

Looking at the templates, none are available after changing the storage location - so there's no apparent way to create a note with a dark background now. 

This error happened the first time I opened the templates section, afterwards there's no error, the list is just empty. The templates folder does exist in the file system and I could not create a template - nothing would happen after clicking "create template". 

![Screenshot_20220817-190130_Butterfly Nightly](https://user-images.githubusercontent.com/1337470/185200055-ce327386-0e0e-42e2-bf95-a4bca9a206a2.png)

Even copying the pre-existing templates from the app internal folder doesn't make them show up in the menu. 

I'm on LineageOS 19 on a Galaxy Note 10 Plus. 

### Version

1.4.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thank you for reporting the bug. I fixed it and will release it in the next days
