### ISSUE TITLE
[Bug]: Inconsistencies when changing document directory

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#255]
### What happened?

When the document directory is changed, existing files aren't moved. This may be intentional (albeit arguably bad, since there's no other easy way to extract the files from the app's internal storage), however the old files are still shown in the quick open menu, but can't be accessed (a new blank file is shown). 

Files can apparently also not be saved or created, neither can templates (see #254).

Folders can be created with the larger file menu, they also appear in the file system. When clicking "create" for a file in the "open" menu, simply nothing happens. 

(Are the errors caught somewere?)

### Version

1.4.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Okay I found the issue. You can't use a directory outside of the documents folder. But I will add a notification that users will get a notification that this folder can't be used

**Comment by CodeDoctorDE** [comment]
Okay,
Seems like flutter file picker doesn't support it currently: https://github.com/miguelpruivo/flutter_file_picker/issues/721#issuecomment-1198600754.
I disable this feature temporarily. The current files can be found in /Android/data/dev.linwood.butterfly

**Comment by solarkraft** [comment]
Can confirm that saving files and templates work when in a sub-directory of /Documents.  
A remaining bug is that the quick open menu still shows files that have been open from another location; actually opening them fails.

**Comment by CodeDoctorDE** [comment]
I disabled it temporarily. I can't get the current document directory from android to test it. I need to test it more and reenable it after that again

**Comment by solarkraft** [comment]
Templates and documents already in the folder also don't appear when changing to it, even after force stopping and deleting the cache.

**Comment by CodeDoctorDE** [comment]
I fixed it now by disabling it on android. Maybe we should add an issue to reimplement it with a safer option. For now the syncing feature should help and the native file system(all files should be stored in `/Android/data/dev.linwood.butterfly`).
1.5 will implement a feature to export everything: https://github.com/LinwoodCloud/Butterfly/issues/269
