### ISSUE TITLE
[Feature request]: Undo/redo buttons as toolbar tools

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#257]
### Is your feature request related to a problem? Please describe

Accessing undo/redo functionality is currently very cumbersome as it's hidden behind the overflow menu (you have to move quite far from the default position, have to wait for the menu to appear, then you can hit the button - but it's not exactly reliable due to the lag issues and covers up a big part of the screen, so you can't even immediately be sure whether the operation succeeded!). 

### Describe your feature request!

Add undo and redo as tools that can be added to the toolbar - this should perfectly complement and extend the existing customizability. 

### Additional context

I'm on a small screen, which makes the overflow menu cover up a large portion of the canvas. While the stroke eraser doesn't work well, this feature is especially important to me for correcting mistakes. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Good idea 👍

**Comment by CodeDoctorDE** [comment]
But how should the undo/redo be triggered?

**Comment by solarkraft** [comment]
I see, this would be new type of "one off" tool - you press the button once to undo something, without it being activated. This doesn't (directly, anyway) collide with the tool settings, since they can also be activated on a long press. 

This raises another interesting idea about "single use" tools - maybe a user might want to use some tools just for one stroke - perhaps for the eraser, highlighter or shapes. But this is not something I directly wish for right now, so I'll spare you the feature request.

**Comment by CodeDoctorDE** [comment]
For now I will implement the first idea. The tool get's activated for this action and instantly deactivated.
