### ISSUE TITLE
[Feature request]: Map stylus button to arbitrary tool

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#258]
### Is your feature request related to a problem? Please describe

I'm using a stylus with a button. I'm happy Butterfly now technically supports receiving button events from it - but it maps it to panning the canvas. This is useless to me, since I already do this using my fingers. I would much rather be able to use an eraser or (future) selection tool to correct mistakes. 

### Describe your feature request!

Add the ability to map the stylus button to an arbitrary tool. 

### Additional context

This would perfectly extend Butterfly's existing strength in tool customizability. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Should this be mapped document dependent or global?

**Comment by solarkraft** [comment]
I'd imagine it as a global setting, I don't see much value in having it document specific. 

Though you could argue that it should be document specific (maybe it's technically necessary, even) since the tools are too. However maybe it would make sense to change that as well ...

**Comment by CodeDoctorDE** [comment]
Globally sounds good. You can type a number for the index of the tool in the behavior settings.

**Comment by CodeDoctorDE** [comment]
Implemented in 1.5.0-alpha.2
