### ISSUE TITLE
[Feature request]: Selection tool

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#259]
### Is your feature request related to a problem? Please describe

After drawing something, I'd like to be able to change its location, scale, rotation and perhaps duplicate or precisely delete it (first 2 being the most important). 

### Describe your feature request!

Add tools for free-form or square selection. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solarkraft** [comment]
I see. Even if it worked for me (see #260), I'd probably prefer the precision and speed of precisely and quickly being able to select all the strokes within an area (with bonus points for being able to choose whether the tool selects everything it touches or everything fully within the selection; I'd usually prefer the latter).

**Comment by CodeDoctorDE** [comment]
Like the interface with the area tool?

**Comment by solarkraft** [comment]
Yes, preferably free-form.
