### ISSUE TITLE
[Feature request]: Layers and object groups.

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/Butterfly#26]
### Describe your feature request!

It would be nice to have layers to toggle visibility, mass delete and limit selection of objects more easily.

Similarly, bundling objects in groups to be movable/deletable together would also help.

I expect these feature to be more important then e.g. animation (#11), but less important than fixing bugs, UX/UI issues and improving performance for scenes with many objects.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Oh yeah, that is my plan in the 1.1 update :) I forgot to create an issue, thanks <3

**Comment by CodeDoctorDE** [comment]
You can try this here https://butterfly-git-feature-layers-linwood.vercel.app/
