### ISSUE TITLE
[Bug]: Can't select elements using touch input

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#260]
### What happened?

> ![image](https://user-images.githubusercontent.com/20452814/185440092-78250276-e0b8-477b-9a75-9661788a46d9.png) You can select elements by clicking on it. The hand tool should be the selection tool

This works neither with my finger, nor with the pen. 

### Version

1.4.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
On my android device (android 12) it works. Do you tried zooming in and open. And what happens if you tap on it. Does it open a menu?

**Comment by solarkraft** [comment]
I have, even with the stroke almost filling the screen it doesn't work, both with "include eraser" disabled and enabled (what's that even supposed to do?). 

Even on the web getting the menu to open was very non-obvious to me. How about activating on a long press or opening it immediately?

**Comment by CodeDoctorDE** [comment]
Can you try moving the canvas zooming in and out and try again?
Long press is already implemented in the dev version

**Comment by solarkraft** [comment]
Wow, I got it to work for the first time by wildly tapping around. It works every few tries. Since often the canvas moves slightly, I could imagine that it tries to process the taps as move gestures (I swear I'm normally tapping, not dragging).

**Comment by CodeDoctorDE** [comment]
If it moves slightly it triggers the scale update event and not the tap event. You need to click very fast.
Does it work better with the dev version (https://preview.butterfly.linwood.dev)?

**Comment by solarkraft** [comment]
It does work with much slower taps, even tapping "from the side" (so it drags a little) works reliably. The problem might be exacerbated by my phone sampling touches at 90 Hz and pen events at 340 Hz.

**Comment by CodeDoctorDE** [comment]
I get the events from the flutter framework. The new version uses the long press event for the context menu and the simple click to select an element.
