### ISSUE TITLE
[Bug]: Highlighter lines contain brighter dots

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#262]
### What happened?

When using a highlighter color (-> transparency), there are bright, round dots where the line segments join. This is more apparent when using the web version due to the lower sampling rate, but it potentially presents an even bigger problem on Android: The more slowly you draw, the more opaque the highlighter line becomes, to the point of letting nothing shine through. That's probably not desirable either for "note" applications; it's definitely not how other apps do it and could be changed at the same time (applying the alpha on the whole line, not the individual segments). 

![IMG_20220818_203343_460](https://user-images.githubusercontent.com/1337470/185469127-f9c1c062-8a53-4de1-a024-3e214cc5af9e.jpg)

![IMG_20220818_203341_166](https://user-images.githubusercontent.com/1337470/185469137-e529a2e4-70f6-4d64-91aa-3e0075f7ec59.jpg)

### Version

1.4.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hmm yeah. I don't know how to fix it...
I draw line by line and on these brighter dots both lines are connecting.

**Comment by solarkraft** [comment]
Is it not possible to apply the alpha on the whole line instead of the individual segments?

**Comment by solarkraft** [comment]
BTW, I do think the effect might be desirable, but for something more like an "air brush" tool (i.e. explicitly requested).

**Comment by CodeDoctorDE** [comment]
The problem is that I draw the lines individually. One solutiion is to use drawPath instead of drawLine but then I can only use one stroke width (that means you cannot use your stylus pressure input)

**Comment by CodeDoctorDE** [comment]
Can you try this?
https://butterfly-git-feature-free-hand-linwood.vercel.app/
