### ISSUE TITLE
[Bug]: Can't upgrade Android app from Github

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#263]
### What happened?

When attempting to upgrade the Android app, for example from 1.4.1 to 1.4.2, installation fails with "App not installed as package conflicts with an existing package". 

The workaround is uninstalling the app, which means losing all data, unless the document path has been changed (one reason #255 matters). 

https://user-images.githubusercontent.com/1337470/185473688-f8d2aaa6-c83e-4247-8e05-613500b24722.mp4

### Version

any recent

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Do you installed the app using the store? You cannot update the app through github if you installed it using playstore/fdroid

**Comment by CodeDoctorDE** [comment]
Okay, I added signing to the apk.
For the last time you need to uninstall it and reinstall it to use the 1.4.3.
After that it should work normally

**Comment by CodeDoctorDE** [comment]
FDroid and Play Store signs the app with their own signing.
That means that you need to uninstall it to use the store versions
