### ISSUE TITLE
[Bug]: Lines erased using stroke eraser reappear

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#265]
### What happened?

Especially when quickly moving the stroke eraser over thin lines, sometimes the lines don't disappear or they re-appear. When reloading the file they are gone, but they can't be deleted otherwise (no panning out of view or drawing over them helps) except with the eraser tool. 

In the video I attempt to erase all lines, first quickly, then more and more slowly. 

https://user-images.githubusercontent.com/1337470/185481082-40e9012e-3574-47cd-b4a9-c998ef2aecc3.mp4

### Version

1.4.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by solarkraft** [comment]
This gets worse when the app is already laggy (see #266)

https://user-images.githubusercontent.com/1337470/185483885-af0455a0-3374-43a8-9d94-885edc03e684.mp4

**Comment by CodeDoctorDE** [comment]
Can you try https://preview.butterfly.linwood.dev, I think I fixed it
