### ISSUE TITLE
[Bug]: Grave slowdowns when many strokes are present

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#266]
### What happened?

Once 1000 or so strokes are in view, the app becomes extremely choppy. Then when I attempt to use the stroke eraser, it straight up freezes. 

The video might look exaggerated, but these effects are easily noticeable while normally hand writing. 

https://user-images.githubusercontent.com/1337470/185483305-9fcb0e88-5299-4d83-85f2-9f03f9874487.mp4

### Version

1.4.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Can you try https://butterfly.linwood.dev?

**Comment by solarkraft** [comment]
The slowdown also seems to appear there. I couldn't try the preview due to a bug preventing drawing after changing the pen's stroke size. Should I open an issue for that?

**Comment by CodeDoctorDE** [comment]
![image](https://user-images.githubusercontent.com/20452814/185763389-3eb2ace2-a56c-44ed-a289-458bff35c8c1.png)
Hmm, I can draw when changing the stroke size.
