### ISSUE TITLE
[Feature request]: Finger as extra tool

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#267]
### Is your feature request related to a problem? Please describe

My stylus only has a single button, but I'd like to be able to activate more tools on demand (stroke eraser + selection tool) to be fully productive. 

When using "pen only input", single finger inputs are unused. 

### Describe your feature request!

The finger could be used as an extra tool, for example an eraser - the app Squid does this and it's a great productivity feature and a good way to compensate for only having a single button on the pen. 

### Additional context

This would really shine once a lasso selection tool is available. 

Its biggest weakness is unreliable palm detection rejection - this keeps causing problems in Squid - but being able to map it to the selection tool should mean fewer issues. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Related to https://github.com/LinwoodCloud/Butterfly/issues/270

**Comment by CodeDoctorDE** [comment]
Hi, do you have a good idea how to implement it with the current implementation in <https://preview.butterfly.linwood.dev>? I don't want to have a difficult implementation and want to support devices that don't have support for stylus inputs

**Comment by CodeDoctorDE** [comment]
Implemented in 1.5.0-alpha.2
