### ISSUE TITLE
[Bug]: Can't pan, only zoom

### ISSUE THREAD

**Issue by solarkraft** [LinwoodCloud/Butterfly#268]
### What happened?

At some point during the usage of the app, usually after many minutes, planning using two fingers becomes unavailable, the gesture only zooms the canvas from the center. 

Reloading the document doesn't help, only restarting the app seems to work. 

I've unfortunately not been able to reliably reproduce this, but it has usually happened during my experiments with lag and erasing strokes. 

### Version

1.4.2

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Fixed in 1.5.0-alpha.1
