### ISSUE TITLE
[Bug]: Zooming using wheel scrolling in web version only zooms in.

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#27]
### What happened?

1. Use https://butterfly.linwood.dev/
2. Create some project and draw something
3. Try issuing wheel up / wheel down events.

Expected: one of the events zooms in, the other zooms out
Actual: scrolling both up and down zoom in.

I don't know what version is in use. Just what's deployed on the public site right now.

### Version

2.0.0-rc.1 (Latest snapshot)

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I think all zoom issues are fixed in the newest version: https://preview.butterfly.linwood.dev
