### ISSUE TITLE
a tool can be added several times [Bug]: 

### ISSUE THREAD

**Issue by ProgrammerLP** [LinwoodCloud/Butterfly#271]
### What happened?

<h1>a tool can be added several times</h1>

<h3>How?</h3>

-You go to the web page, maybe this bug is also on other platforms, but found it by using the web version
-click the plus in the toolbar and select any item, which is already in the toolbar

![grafik](https://user-images.githubusercontent.com/101939228/185763644-fc48eea4-72b9-49cd-becd-f087cdd3d819.png)

I hope I could make myself useful

### Version

i think it was V1.4.3

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That's intentional. You can add a "title pen", a "normal text pen" and an "underline pen"

**Comment by ProgrammerLP** [comment]
ok but they do the same, or not?

**Comment by CodeDoctorDE** [comment]
No, you can change the settings of these painters
