### ISSUE TITLE
[Bug]: Drawing while zooming using mouse wheel works poorly.

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#29]
### What happened?

1. Go to https://butterfly-git-feature-draw-home-page-linwood.vercel.app
2. Start drawing a stroke by pressing and holding left mouse button (do not release it yet)
3. Move the mouse, observe a line appearing.
4. Without releasing the left mouse button, use wheel to zoom in
5. Move mouse further, to continue the stroke.

Expected: new stroke segments appears where the mouse cursor is positioned

Actual: zoom is misaligned (#19), resets back when mouse is moved (like in #21), and a spike is added to the current stroke. Unlike #20, this additional segment is a part of project and stays so after refreshing. 

### Version

dev deployment

### Test it on thedevelopment version

- [X] I tried this bug in the newest development version.

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks <3 for all this work to test the app.
