### ISSUE TITLE
[Bug]: Can't insert PDFs in windows and Android

### ISSUE THREAD

**Issue by surferjoeit** [LinwoodCloud/Butterfly#302]
### What happened?

Whenever i try to insert a PDF i get this error:
![Screenshot_2022-10-23-10-38-21-32_8e38dcdfba96899c92b61f571a6ea0ea](https://user-images.githubusercontent.com/26968284/197502762-f468a840-11b5-4780-8734-c8ebb054a1a4.jpg)

### Version

1.5.0

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Bug confirmed. Will be fixed in 1.5.1

**Comment by CodeDoctorDE** [comment]
Fixed in 1.5.1
