### ISSUE TITLE
[Feature request]: Command line for data path

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#304]
### Describe your feature request!

Hi, thank you for making this good app.
I want to use the Butterfly app on USB (portable mode)
Butterfly use ~/Documents folder to save projects
I need a command line to change data path, for example:
```
butterfly.exe -data-path=".\MyData"
```
Please add this.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Good idea, I will add it.

**Comment by CodeDoctorDE** [comment]
Added in 1.6.0-alpha.0

**Comment by xmha97** [comment]
Thanks.

**Comment by xmha97** [comment]
@CodeDoctorDE What do you think about adding this file to the portable version?
[_Portable.cmd](https://github.com/LinwoodCloud/Butterfly/files/10456766/_Portable.zip)

**Comment by CodeDoctorDE** [comment]
Sure, maybe for the linux portable too?
I would call it `start.bat` and for linux `start.sh`?

**Comment by xmha97** [comment]
> I would call it `start.bat` and for linux `start.sh`?

It's a good idea.
Add `start.bat` and `start.sh`.

**Comment by CodeDoctorDE** [comment]
Added. Will be released in 2.0

**Comment by xmha97** [comment]
Thanks. 👍
