### ISSUE TITLE
[Bug]: Add app icon on the Windows control panel

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#305]
### What happened?

Add app icon on the Windows control panel

![image](https://user-images.githubusercontent.com/23485114/199274492-730baf35-762e-4d35-81bb-f47c0766ef03.png)

(also delete app version on the name)

### Version

1.5.1

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Added in 1.6.0-alpha.0
