### ISSUE TITLE
[Bug]: Installer doesn't offer an option to install for all users

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#306]
### What happened?

Usually, in enterprise environments, restrictions are applied that do not allow apps to be installed in Program Files.
Please add this option on installer:
- Offer an option to install for all users.

Like Simplenote app:
<img width="384" alt="image" src="https://user-images.githubusercontent.com/23485114/199283837-f1760d09-6ecf-410c-8bf9-d267f7449321.png">

### Version

1.5.1

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
![grafik](https://user-images.githubusercontent.com/20452814/199429968-263b3a84-38b0-4f19-8a8c-6820d21de36a.png)
(it's german)

Added in 1.6.0-alpha.0
