### ISSUE TITLE
[Bug]: The "Start in full screen" does not work

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#307]
### What happened?

Hi,
The "Start in full screen" does not work on the Windows:

https://user-images.githubusercontent.com/23485114/199293053-8f7743f5-27fd-4d98-9bd2-2e0c26611955.mp4

### Version

1.5.1

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thanks for reporting bugs and request features!

**Comment by CodeDoctorDE** [comment]
Fixed in 1.6.0-alpha.0

**Comment by xmha97** [comment]
Thanks.
