### ISSUE TITLE
[Feature request]: Make MSIX package and upload this app to Microsoft Store.

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#308]
### Describe your feature request!

Please make MSIX package and upload this app to Microsoft Store.
https://learn.microsoft.com/en-us/windows/msix/overview

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
For this I need to get a developer account on microsoft and need to pay something. I don't know if it's worth for a store that nobody uses

**Comment by xmha97** [comment]
You are right, I will close this issue.
