### ISSUE TITLE
[Bug]: Spinning Ring never opens previously created note. 

### ISSUE THREAD

**Issue by cdedert** [LinwoodCloud/Butterfly#309]
### What happened?

I create a note on Android and sync it to my Nextcloud webdav, but I can't re open on this device, or any other Android device. 

### Version

1.5.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This can happen if you have a corrupted file. Can you send me the content of the file in nextcloud?

**Comment by cdedert** [comment]
I'm just testing this app. So there just a few test notes to test the sync.
Should I delete this folder and start over? 
![Screenshot_20221102-070026_Nextcloud](https://user-images.githubusercontent.com/73313622/199484944-a8b06b2f-6e27-48ca-b9ae-e46fe5addf49.jpg)
![Screenshot_20221102-070033_Nextcloud](https://user-images.githubusercontent.com/73313622/199484948-28dd59a4-9738-4826-96ab-8edbeefe093f.jpg)
![Screenshot_20221102-070042_Nextcloud](https://user-images.githubusercontent.com/73313622/199484951-5f8c70fa-76a6-4c39-bdac-9a666277da4d.jpg)

**Comment by CodeDoctorDE** [comment]
You don't need to delete it.
Just send the file that causes the bug

**Comment by CodeDoctorDE** [comment]
I added an error page if the loading of the document fails.
Can you try updating to the newest nightly version?

**Comment by CodeDoctorDE** [comment]
Can you try the latest alpha?
There should be an error message when opening the document

**Comment by CodeDoctorDE** [comment]
Closed because of inactivity.
Please open another issue if it appears again
