### ISSUE TITLE
[Feature request]: [Windows] 32-bit

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#311]
### Describe your feature request!

Is it possible to support 32-bit systems?
I want to run this app on an old tablet.

![image](https://user-images.githubusercontent.com/23485114/201499646-e1ce0857-f666-433f-b7d7-c1cdcb452de1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
This is currently not supported by flutter:
https://github.com/flutter/flutter/issues/37777
You can upvote this issue to show the flutter team, that you need it

**Comment by xmha97** [comment]
Ok, I'm closing this issue.

**Comment by CodeDoctorDE** [comment]
I don't know if windows officially supported 32-bit active.
The architecture is a bit older.
If you want to use it anyways, you can open the web version with the 32-bit chromium app https://chromium.woolyss.com/download/de/

**Comment by xmha97** [comment]
Thanks.
