### ISSUE TITLE
[Feature request]: Thoughts about eraser tool

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/Butterfly#32]
### Describe your feature request!

For new Butterfly users it may be not obvious that it is a vector graphics editor. In particular, eraser tool (at least the way it works now) is less recommended way to delete content.

It may be helpful to show tutorial-esque message hinting users that objects can be selected and deleted in view mode.

In future there can be advanced feature of automatically detecting that users wants to delete scene object based on the use of eraser tool, to prompt conversion of that action to actual deletion of scene object.

---

Maybe eraser tool's primary function should actually be modification and removal of scene objects, not adding separately selectable eraser strokes.
Current implementation of eraser tool may actually be a special pen mode instead.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
We have already a delete eraser, named path eraser which should simplfy the deletion of paths. I will look at it after fixing all bugs

**Comment by CodeDoctorDE** [comment]
I added a warning to the docs https://docs.butterfly.linwood.dev/docs/1.0/painters/eraser

**Comment by CodeDoctorDE** [comment]
I will add a new eraser that only remove some part of the path. This should resolve the problem with the eraser tool.
