### ISSUE TITLE
[Feature request]: Mipmap for Windows icon

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#329]
### What happened?

Hi, Butterfly icon on Windows is only 256x256.
Please add another size icon. (Mipmap)

![image](https://user-images.githubusercontent.com/23485114/213448349-3d73f698-35c2-407a-9de7-d5768b514470.png)

**Add:**
- 128x128
- 48x48
- 32x32
- 24x24
- 16x16

Thanks.

---

You can use this app for making icons:
Greenfish Icon Editor Pro

Installable Version:
http://greenfishsoftware.org/gfie.php

Portable Version:
https://portableapps.com/apps/graphics_pictures/greenfish-icon-editor-pro-portable

---

### Version

1.6.0.57

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I created the icon on a free online converter.
Can I ask why you need them? On my machine I don't see a difference in the start menu.

**Comment by xmha97** [comment]
Check the icon on the taskbar:
![image](https://user-images.githubusercontent.com/23485114/215282322-c8b383a3-acc6-40fa-abe5-4b63024a6f30.png)
[Mipmap.zip](https://github.com/LinwoodCloud/Butterfly/files/10527884/Mipmap.zip)
[256.zip](https://github.com/LinwoodCloud/Butterfly/files/10527885/256.zip)

**Comment by CodeDoctorDE** [comment]
That's an argument.
I don't know why windows doesn't want to resize it correctly

**Comment by xmha97** [comment]
Thank you for paying attention to this issue.
See the issue below, I have already mentioned this problem about the Windows 10 start menu for LosslessCut app.
https://github.com/mifi/lossless-cut/issues/778

**Comment by CodeDoctorDE** [comment]
I want to redesign the icon for the Butterfly 2.0 update, with that I will add these new mipmap

**Comment by xmha97** [comment]
Thanks 🙏👏

**Comment by xmha97** [comment]
Thanks 🙏
