### ISSUE TITLE
[Bug]: With Greek characters

### ISSUE THREAD

**Issue by PlematiasXenofon** [LinwoodCloud/Butterfly#336]
### What happened?

A bug happened! If a .bfly file is inside a folder with a name in Greek characters, or the file itself is named with Greek characters and i try to open it throught the app, the screen freezes and turns to grey.

<img width="206" alt="Στιγμιότυπο οθόνης 2023-02-09 172257" src="https://user-images.githubusercontent.com/93429811/217856333-8d2a1427-4e31-46db-a3ad-e075d24a9175.png">

<img width="947" alt="Στιγμιότυπο οθόνης 2023-02-09 172619" src="https://user-images.githubusercontent.com/93429811/217856675-5c4243c9-0369-48f3-a7dd-7a9ca48d12f9.png">

### Version

1.6.1

### Platform

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Hi,
I'm using the default file loader from dart that access the os file loader.
Are greek characters allowed as directory names? As far as I know, you can only use A-z,0-9

**Comment by PlematiasXenofon** [comment]
Οk, i understand what you are saying, but i think that the freeze could be fixed with an error message that explains the restrictions of the file name , since its not clear to the user what the problem is exactly when it freezes.

**Comment by CodeDoctorDE** [comment]
Typically there should be a global error message screen that catches everything.
I will look later in the code why it doesn't catch the error. Thank you for reporting!

**Comment by CodeDoctorDE** [comment]
Added in 2.0.0-alpha.0
