### ISSUE TITLE
[Bug]: The app is stuck after setting the size of grid to zero

### ISSUE THREAD

**Issue by knwng** [LinwoodCloud/Butterfly#337]
### What happened?

Hi, I'm new to this app and trying to create lines with grid(I didn't find any pre-defined lined background).

But as shown in this pic, the app is stuck after setting x or y to zero.
![WechatIMG2921](https://user-images.githubusercontent.com/26247277/219877051-ecb372d4-f0f8-4ca1-9e2a-d67e5d686d6e.jpeg)

I'm using a Matepad, which is actually running on the Harmony system, something similar to Android but not exactly the same. I'm not sure if that's the reason.

### Version

1.6.1

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I can replicate it. I will fix it. For now, try using a size that is > 0

**Comment by CodeDoctorDE** [comment]
When you want a real background, try clicking long on the background with the hand. Then you can choose your favourite background

**Comment by CodeDoctorDE** [comment]
Fixed soon in 1.6.2

**Comment by knwng** [comment]
> If you want a real background, try clicking long on the background with the hand. Then you can choose your favourite background

OK, thx for the tip! But long click doesn't work for me. Double clicks worked.
