### ISSUE TITLE
[Feature request]: Add monochrome icon

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#339]
### Describe your feature request!

Please support the Themed Icon.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

![Screenshot_2023-02-20-16-13-59-923_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/220111856-60445f38-a558-4c10-857d-69ab400356ab.jpg)

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
We are currently build a new logo for Butterfly 2.0
Monochrome icons for android looks like a good addition

**Comment by xmha97** [comment]
Ok, thanks for the new icon.

**Comment by xmha97** [comment]
Thanks 🙏

**Comment by CodeDoctorDE** [comment]
you're welcome :)

**Comment by xmha97** [comment]
Hi, the new icon is very nice. 👍

**Comment by xmha97** [comment]
> Thanks, it will be available in the first alpha (2.0.0-alpha.0)

I'm waiting for the alpha version:

![Screenshot_2023-03-25-14-49-52-974_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/227714486-4956e45f-131e-4512-8292-b435fc74d4e1.jpg)
