### ISSUE TITLE
[Feature request]: Keyboard shortcuts for presentation mode

### ISSUE THREAD

**Issue by ProgrammerLP** [LinwoodCloud/Butterfly#347]
### What happened?

Exiting presentation mode with ESC key doesn't work

### Version

newest preview

### Platform

Web

### Relevant log output

```shell
---
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
The presentation mode is very new. It's not ready for production.
But yeah, I had this on my todo list
