### ISSUE TITLE
[Feedback]: 

### ISSUE THREAD

**Issue by ProgrammerLP** [LinwoodCloud/Butterfly#348]
### Is your feature request related to a problem? Please describe

Presentation Mode and RichText is very user unfriendly

### Describe your feature request!

Improve the user-friendliness

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Please use the discord or the discussion feature for this.
Please report only bugs and feature requests here.
