### ISSUE TITLE
[Bug]: Linwood Logo not showing on website

### ISSUE THREAD

**Issue by Sarraj-Sahar** [LinwoodCloud/Butterfly#360]
### What happened?

The Linwood Logo is not showing on the Butterfly website (https://docs.butterfly.linwood.dev). I have tried accessing from different devices and it's still not showing. 

<img width="881" alt="image" src="https://user-images.githubusercontent.com/82158584/227721867-552d46fa-b982-4eb6-a7a4-4e2aeeada449.png">

Side Note: 
I know it's a whole different project but the logo works fine for the Linwood Flow website. That's what made me sure it wasn't a connection problem and the logo image is not showing as it should.

### Version

1.6.1

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Oh thanks.
I rebuilt the main linwood website https://linwood.dev and changed the path of the logo.

**Comment by CodeDoctorDE** [comment]
Fixed!
