### ISSUE TITLE
[External]: Surface Pen Third Button Support

### ISSUE THREAD

**Issue by LucBennett** [LinwoodCloud/Butterfly#364]
### Is your feature request related to a problem? Please describe

Butterfly supports shortcuts for two buttons but the Microsoft Surface pens have a side button and an eraser.

### Describe your feature request!

It would be nice to use both the side button for things like the hand tool and the eraser to erase.

### Additional context

The Microsoft Pens use the creatively named Microsoft Pen Protocol. 
Onenote supports three buttons out of the box. Xournal++ has a menu option to set up the shortcuts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Yes, currently flutter does not support reading this protocol (see issue #238: https://github.com/LinwoodCloud/Butterfly/issues/238#issuecomment-1206721877).
Can you try it using the web version? https://butterfly.linwood.dev
