### ISSUE TITLE
Use new icon on GitHub

### ISSUE THREAD

**Issue by xmha97** [LinwoodCloud/Butterfly#366]
### Describe your feature request!

Hi, please use the new icon on GitHub.

![Screenshot_2023-04-09-05-44-33-905_com github android](https://user-images.githubusercontent.com/23485114/230751008-3fb3a483-aaa0-4c28-bfe1-e1f090e20e8d.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Thats the linwood Logo. The Butterfly Logo was changed
