### ISSUE TITLE
[Bug]: Drawing while pinch-zooming does not work.

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#45]
### What happened?

#20 is said to be resolved. Yet it still see it on Android, even with the recent commit:

https://user-images.githubusercontent.com/173219/141698848-9f65948c-d2bd-49ec-9441-84c885de42f5.mp4

1. Open Butterfly.
2. Start drawing by touching the screen and moving finger.
3. Without releasing the finger, also touch second finger to zoom in/out without interrupting the stroke

Expected:

It zooms in/out using first (actively drawing) finger as pivot point if second finger is moved. It scrolls the canvas around if both fingers are moved (such as after finishing the temporary zoom/pan mode it would continue drawing the stroke without any long straight segments).

Actual:

It removes already drawn part, then starts drawing a zigzag line between fingers.

Note:

Filling area between fingers (using a proper closed curve, not a zigzagging line) can be a special, distinct touchscreen-exclusive drawing tool. 

### Version

build from cebe8156118e1f61fe8647a6ee4a9c1cd15f4cfa, devel branch

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
I think it's a bit complicated to have the first finger as pivot point. Currently I cannot get the first finger so simple. Is it okay, if I disable the drawing when zooming?

**Comment by CodeDoctorDE** [comment]
Confirmed on all platforms

**Comment by vi** [comment]
> Is it okay, if I disable the drawing when zooming?

My suggested scheme interrupts drawing when zooming, i.e. no new segment should be added to stroke when both fingers are touched down. Or did you mean "disable the zooming when drawing"?

> Currently I cannot get the first finger so simple.

Finger, which position on screen is closest to the last remembered position of the lone (pre-zoom) finger should be considered first (and that position coordinates is to be updated).

> I think it's a bit complicated to have the first finger as pivot point.

Not doing it (one way or another) would result in unintended stroke segments being added to scene after zooming is done.

What is the complication? Is Flutter not multitouch-ready, so your program receive only partial information about multi-touch events? Or are algorithms and mathematics too complex to implement?

**Comment by CodeDoctorDE** [comment]
> What is the complication? Is Flutter not multitouch-ready, so your program receive only partial information about multi-touch events? Or are algorithms and mathematics too complex to implement?

I think, currently I only get a pointer if the user moves the pointer. I can google longer, but currently I cannot find a solution which helps me implement this

**Comment by CodeDoctorDE** [comment]
https://api.flutter.dev/flutter/gestures/PointerEvent/pointer.html maybe this? I will try it

**Comment by vi** [comment]
Even with no special fields, coordinates of all events may be monitored and receiving an event from a touchscreen with substantially different coordinates while having not previously received "up" event from previous location can imply that multi-touch is active and the new event is the second finger.

`pointer` field is of course helpful, if it works properly. Linked `PointerEvent` API description suggests that Flutter is multi-touch-ready.

**Comment by CodeDoctorDE** [comment]
I will add options how to interact with multiple inputs to customize if you want to use the second input as zooming/moving or as new input to draw
