### ISSUE TITLE
[Bug]: Zooming out, then back in does not return viewport to origin

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/Butterfly#46]
### What happened?

https://user-images.githubusercontent.com/173219/141699227-daefb01b-4a61-4ce9-af84-da077ef4d138.mp4

1. Open the app
2. Draw something
3. Zoom out multiple times
4. Zoom back in to 100%.

Expected:

It zooms using current viewport center as pivot point. Zooming back in after zooming out results in no change to viewport.

Actual:

Pivot point is inconsistent: it switches to top left corner at some point in zooming out. Zooming back in results in a different viewport position where the drawing may be out of visibility.

### Version

build from cebe8156118e1f61fe8647a6ee4a9c1cd15f4cfa , devel branch

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Now, temporary it goes up if you zoom out. Currently I don't have the idea to fix this.
If anyone is interested, the corresponding code can be found here: https://github.com/LinwoodCloud/butterfly/blob/develop/app/lib/cubits/transform.dart#L16

**Comment by vi** [comment]
> Currently I don't have the idea to fix this.

Zoom out, then make such position, so that scene position that was at the center of viewport remains center of the new viewport. May require solving a simple equation.

> https://github.com/LinwoodCloud/butterfly/blob/develop/app/lib/cubits/transform.dart#L16
> oldCursor, newCursor

What is a "cursor"?

**Comment by CodeDoctorDE** [comment]
`cursor` is your current local mouse position or your current finger position. If you click on the zoom in/out/reset button, the cursor is viewportSize / 2 (center). See: https://github.com/LinwoodCloud/butterfly/blob/develop/app/lib/views/main.dart#L465

**Comment by vi** [comment]
> I try to get the distance to the left top corner from the old size and add the same distance to the new size

Terms "distance" and "size" are ambiguous in this context. Do you mean scene coordinates or viewport coordinates?
Does the program have clear abstraction of those two coordinate systems (with proper, convenient conversions between them)?

**Comment by CodeDoctorDE** [comment]
The cursor are local positions. They are independent from the current scale of the canvas. I divided this position with the old scale and the new scale to get the y distance and the x distance to add them to the current position

**Comment by CodeDoctorDE** [comment]
I pin this issue if anyone has interest to create a pull request. I don't have an idea anymore how I can fix this

**Comment by vi** [comment]
With zooming not returning back, it feels as if the "infinite" canvas actually hits some invisible "border" on the way, making it actually finite.

**Comment by CodeDoctorDE** [comment]
I think the formular or the position isn't 100% accurat. These small unaccurat numbers will get bigger if you zoom out.
Sorry, I tried everything out and cannot find a way how to fix this

**Comment by vi** [comment]
Sometimes when zooming from 20% to 10% it goes way out of range and I cannot find my content by just panning around or zooming. Only "Waypints -> Origin" restores the viewport.

**Comment by CodeDoctorDE** [comment]
Try it out: https://preview.butterfly.linwood.dev
