### ISSUE TITLE
[Bug]: Text entry tool asks to input text multiple times

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#47]
### What happened?

https://user-images.githubusercontent.com/173219/141699386-4e16c6de-47f4-45b7-b544-fcdb0781aee5.mp4

1. Open the app
2. Switch to text tool
3. Tap on screen single time.
4. Text entry modal dialogue shows up
5. Input the text and press OK

Expected:

It returns to the main view, revealing the newly added text.

Actual:

It shows another text input dialogue. Cancelling it returns to the main view, typing text there adds another text element to the scene.

### Version

built from cebe8156118e1f61fe8647a6ee4a9c1cd15f4cfa , devel branch

### Platform

Android

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
The issue is only on mobile.

**Comment by vi** [comment]
In the [web version](https://butterfly.linwood.dev) it also shows input dialogue multiple time sometimes.

Try slowly moving mouse cursor across canvas, then long-press left button. It may show the dialogue window twice.

It also shows the dialogue when I press right mouse button, which is not very expected.

**Comment by CodeDoctorDE** [comment]
Okay I see. Thanks, I will try to fix it
