### ISSUE TITLE
[Feature request]: Multiline text input

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#49]
### Describe your feature request!

Both Android and Web version of Butterfly seem to allow to input only one line of text at a time.

This seems too limiting.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
It's already possible. Press enter to create a new line in the input dialog

**Comment by vi** [comment]
Indeed, I re-checked on Android and it allows multiple lines.

But on https://butterfly-git-feature-draw-home-page-linwood.vercel.app/ I can type only a single line.

**Comment by CodeDoctorDE** [comment]
This branch isn't active anymore. Try https://butterfly.linwood.dev for the production and https://preview.butterfly.linwood.dev for the develop branch

**Comment by vi** [comment]
Indeed, butterfly.linwood.dev version, which only got updated after forced page reload (Ctrl+F5) can do multi-line text (although Ctrl+Enter won't confirm input as I expected, maybe I'll create issue about it someday).

There are unrelated new issues with butterfly.linwood.dev version (don't know which exact version it is: #50). Although it is called "production" and "release candidate", it unfortunately feels rather far from done.
