### ISSUE TITLE
[Bug]: Missing version information in about window

### ISSUE THREAD

**Issue by vi** [LinwoodCloud/butterfly#50]
### What happened?

1. Open Butterfly
2. Go to Settings->Information
3. A windows with Butterfly logo and name opens

Expected:
Version number (simple for release, beta or release candidate versions, with a Git commit number for dev versions) is displayed.

Actual:
Only static info is displayed.

![q](https://user-images.githubusercontent.com/173219/141841096-d230f44c-6000-44d8-8e85-cb4440962b5b.png)

### Version

butterfly.linwood.dev

### Platform

Web

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Good idea. I added this dialog only for the license page, but this empty space can be used.

**Comment by CodeDoctorDE** [comment]
The current version is 1.0.0-rc.3, the main branch

**Comment by vi** [comment]
Version number shows up, but it is hard to copy it from that window (at least in browser version).

If it is tricky to have a proper text field there (e.g. like in "Enter the text" dialogue, but not editable) then a dedicated Copy button may be advisably.

**Comment by CodeDoctorDE** [comment]
I added a copy button. If you click on it, you get the version in your clipboard.
