### ISSUE TITLE
[Bug]: "Open" doesn't show notes when full screen

### ISSUE THREAD

**Issue by Redpillbug** [LinwoodCloud/Butterfly#79]
### What happened?

It works fine when the window is scaled to it's default size, but when full screen is triggered, the "Open" option doesn't show any notes.

### Version

1.0.0

### Platform

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Okay, it seems it only appears on linux. Which distro do you use and do you use deb or AppImage?

**Comment by Redpillbug** [comment]
I tried deb. Should I try different install options?

**Comment by CodeDoctorDE** [comment]
Can you try using the portable version in zip format?

**Comment by Redpillbug** [comment]
I tried the portable version after deleting the program, and the problem still exist. I use Linux Mint 20.2 Cinnamon.

**Comment by CodeDoctorDE** [comment]
Okay, I will look at it after I setup my vm

**Comment by Redpillbug** [comment]
quick update... The Nightly version doesn't seem to suffer the same problem. (it works fine)

**Comment by CodeDoctorDE** [comment]
strange...
Then I know what's it does this error: https://github.com/LinwoodCloud/Butterfly/compare/main...develop#diff-dc6a3e6096c7a1071879437bd6baab736deac8d48abae66f7ac947fcd38a424bR60
it seems that the app loads the files after you closed the dialog. Nice that works for you. The nightly version has no bugs currently and should published soon.
