### ISSUE TITLE
[Feature request]: Syncing

### ISSUE THREAD

**Issue by CodeDoctorDE** [LinwoodCloud/Butterfly#88]
### Describe your feature request!

First of all, thanks for the awesome app and design specially being multy platform.
I use the app on my android, and(want to) use the app on my (future) touchscreen linux tablet.
It would be awesome if I can synch the app between my devices without clicking export and go to directory every time.
Some automated, or one touch syncing with clouds (for example next cloud) would be awesome.

Discussion in #87 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
Nextcloud WebDav Docs: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html

**Comment by Shahin-rmz** [comment]
An idea would be, that butterfly saves it's XML on nextcloud/owncloud instance and with different clients, read from that data.

**Comment by CodeDoctorDE** [comment]
Yeah, I will reimplement the file system dialog to allow adding cloud directories and add files in it.

**Comment by Shahin-rmz** [comment]
Thanks.
Waiting for that.

**Comment by Shahin-rmz** [comment]
[This](https://github.com/floccusAddon) project might be interesting, their approach to cloud syncing is interesting.

**Comment by CodeDoctorDE** [comment]
I think the built in webdav is a bit better. This project uses the bookmark app in the nextcloud store. WebDav can be used with other cloud providers than nextcloud.

**Comment by Shahin-rmz** [comment]
> I think the built in webdav is a bit better. 

agree.
WebDav is more global and can be used on many clouds.

**Comment by Shahin-rmz** [comment]
[Joplin](https://github.com/laurent22/joplin/blob/dev/readme/terminal.md) is a famous note taking app.
The way they save server side app is to save their encrypted files inside a folder via CalDav method.
I think it will be good inspiration if you want to take a look.

**Comment by Shahin-rmz** [comment]
Nice job.
Congratulations and thanks.
