### ISSUE TITLE
[Feature request]: Replace label with text field

### ISSUE THREAD

**Issue by jamesduen** [LinwoodCloud/Butterfly#97]
### Is your feature request related to a problem? Please describe

N/A

### Describe your feature request!

- [x] #124
- [ ] #125
- [ ] #247 

### Additional context

Currently if I past bulk text it will all display on a single line, unless there are carat return lines in the copied text. Then it will show on a second or more lines, centered below the top line. It would be very helpful to have the ability to click-and-drag a box that the text will word wrap inside of.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CodeDoctorDE** [comment]
That sounds good. How do you want to add the box?
Another option can be a slider with the max width to control it

**Comment by jamesduen** [comment]
To be fair, I'm not sure how it should be added. Possibly as an option to the text tool itself. I imagine you could add a width/height slider in the edit option for more fine control, but I envisioned a click-and-drag approach similar to how image editing software allows one to select an area.

**Comment by CodeDoctorDE** [comment]
Interesting, area is a feature that I want to add in the next version. It should simplify the export function of images and enable pdf export. For now, the basic new line feature can do it temporarily.
